version: "3.8"

services:

  vaulwarden:
    image: vaultwarden/server:alpine
    container_name: vaultwarden
    env_file:
      - .env
    volumes:
      - vaultwarden:/data
    depends_on:
      - postgres
    networks:
      - proxy
      - vaultwarden
    environment:
      DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD:-secret}@postgres/${DB_DATABASE}'
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`${APP_DOMAIN:-vaultwarden.localhost}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=web"


  postgres:
    image: postgres:15-alpine
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - vaultwarden
    ports:
      - 5432:5432
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'

networks:
  vaultwarden:
    driver: bridge

  proxy:
    external: true

volumes:
  pgsql:
    driver: local
  vaultwarden:
    driver: local
